name = "DAGSieves"
uuid = "fb6ee709-3ae0-424c-bc22-4b7d895840c4"
authors = ["Luca Mondada <luca@mondada.net> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
DataStructures = "0.18"
julia = "1.2"
